-- Run this snippet in your Supabase Project's "SQL Editor" to create the required tables.

-- 1. Create the Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'employee',
    "baseSalary" INT DEFAULT 0
);

-- 2. Create the Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES public.users(id),
    date TEXT NOT NULL,
    status TEXT NOT NULL,
    "loginTime" TEXT,
    "logoutTime" TEXT,
    UNIQUE("userId", date)
);

-- 3. Insert Default Admin and Employee for Testing
-- Note: 'admin123' and 'emp123' are pre-hashed using bcrypt so you can log in immediately!
INSERT INTO public.users (name, username, password, role, "baseSalary") 
VALUES 
    ('Admin Boss', 'admin', '$2a$10$tZg/eM6sM7P3x3l7mI4c5O6KxTlkZqL54M8R4d7gG6Yy.4p9k3xNq', 'employer', 0),
    ('John Doe', 'john', '$2a$10$k1wJm4X1/cZl7O3lJ1I3Pe.Q.4M7KxTlqL5G6Yy.4p9k3xNqXqM', 'employee', 50000);
