-- Run this snippet in your Supabase SQL Editor to add the Advanced Enterprise Features!

-- 1. Create the Leaves Table
CREATE TABLE IF NOT EXISTS public.leaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES public.users(id),
    "startDate" TEXT NOT NULL,
    "endDate" TEXT NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending' -- Can be Pending, Approved, Denied
);

-- 2. Create the Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "adminId" BIGINT NOT NULL REFERENCES public.users(id),
    "action" TEXT NOT NULL,
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Add Geolocation capabilities to Attendance
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "clockInLocation" TEXT;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS "clockOutLocation" TEXT;
